---
title: Natalia Flores's CV
format: html
---


[Business Analytics Consultant]  

<div id="webaddress">
<a href="mailto:[Your Email]">[Your Email]</a> |
<a href="[Your LinkedIn URL]">LinkedIn</a> |
<a href="[Your GitHub or Portfolio URL]">Portfolio</a>
</div>

## Profile

[Current Student pursuing a Bachelor of Science in Business Analytics and a minor in Finance from Brigham Young University - Idaho. I am eager to contribute my skills and passion for data-driven decision-making to your team.

I possess proficiency in Microsoft Office tools, including Word, PowerPoint, Teams, and Excel, and I am skilled in Power BI for data visualization and analysis. My strong communication and interpersonal abilities, coupled with my leadership and teamwork skills, allow me to excel in collaborative environments. My commitment to excellence drives me to succeed in fast-paced settings while maintaining a keen attention to detail.]

## Education

`[April 2025]`  
__[Bachelors Degree in Business ANalytics]__, [Brigham Young University - Idaho], [Rexburg, Idaho]  
- Minor/Specialization: [Finance]
- Relevant Courses or Focus Areas: [Data Science Certificate]

## Professional Experience

### [Quality Assurance Auditor]
__[Brigham Young University], [Rexburg, Idaho]__  
`[Jul 2023] - [Present]`
- [Upgraded quality of service by 80% through auditing 50+ calls, chats, and tickets each week]
- [Improved weaknesses in service by giving feedback to 8+ employees every week resulting in fewer callbacks from customers]

### [Asset & Wealth Management]
__[Goldman Sachs], [Salt Lake City, Utah]__  
`[Jun 2024] - [Aug 2024]`
- [Automatized a process to make reports come out faster by reducing production time from 20 hours to just 1 hour]
- [Helped customers understand and pick the best investment option to increase their revenues]

## Volunteer Experience

### [English Teacher]
__[BYU Pathway Worldwide], [Lima, Peru]__  
`[Oct 2021] - [Dec 2021]`
- [I taught English as a second language to Spanish-speaking students with a variety of backgrounds and ages. We used English Connect 1, 2, and 3.]

### [Volunteer Staff]
__[Helping Hands], [Lima, Peru]__  
`[Dec 2021]`
- [We helped clean the beaches in the area of Lima-Peru.]

## Skills

- Languages: [Fluent in Spanish and English].
- Technical Skills: [Excel, R, Python, SQL, Power BI, Alteryx].
- Key Competencies: [Management, Leadership, Strategic Thinking].
- Specializations: [Finance, Data Science].

## Certifications

- [Data Science], In Progress [April 2025]
- [Business Fundamentals], In Progress [April 2025]

---

_Last updated: December 2024_